on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master  

  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 10 3 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep:latest
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci 
